package telegrambot.collector_bot.repository;

public enum ChatState {
    ADD_NEW_DEBT,
    AWAITING_DEBTOR_USERNAME,
    AWAITING_DEBT_SUM,
    AWAITING_DEBT_DESCRIPTION,
    SAVING_DEBT, AWAITING_COMMAND, ALL_DEBTS, CHANGE_DEBT_SUM, CHANGE_DEBT_DESCRIPTION, AWAITING_DEBT_CURRENCY, GET_MY_DEBTS,
}
